config/routes.rb
Rails.application.routes.draw do

    root "welcome#home"
    get '/signup' => 'users#new'
    get '/login' => 'session#new'
    post '/login' => 'session#create'
    get '/auth/facebook/callback' => 'session#create'
    get '/logout' => 'session#destroy'

    get '/users/users_with_most_requests' => 'users#users_with_most_requests'
    get '/requests/finished_requests' => 'requests#finished_requests'
    get 'requests/unfinished_requests' => 'requests#unfinished_requests'
  #  get '/requests/whatever' => 'checklists#something'




    resources :requests, only: [:create, :destroy, :edit, :update] do
      resources :users, only: [:show]
     end

     resources :checklists, only: [:index, :show, :create, :update, :destroy] do
       resources :requests, only: [:new, :show, :edit, :update, :destroy]
     end

     resources :users, only: [:create, :destroy, :edit, :update, :show] do
       resources :checklists, only: [:new, :edit, :show, :update, :destroy]
     end

     resources :users do
       resources :requests, only: [:show, :edit]
     end

     resources :users_requests, only: [:update]

     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   end

app/models/user.rb
class User < ApplicationRecord
    validates :password, confirmation: true
    validates :name, presence: true
    validates :email, presence: true
    validates :email, uniqueness: true


    has_secure_password

    has_many :checklists
    has_many :users_request
    has_many :requests, through: :users_request

    def self.find_or_create_by_omniauth(auth_hash)
        where(email: auth_hash["info"]["email"]).first_or_create do |user|
          user.password = SecureRandom.hex
          user.name = auth_hash["info"]["name"]
        end
    end

    def checklist_requests(user_checklist)
       if checklists.include?(user_checklist)
         user_checklist.requests
      else
           []
       end
    end

    scope :users_with_most_requests, -> { User.joins(:requests).group('users.id').order('count(users.id)desc').limit(1)}

    #limit() ?
    #first ? (can't use first or last in scope method)
    # Most?
    # {where(most: most)}
    # booleans?
    #select{ |checklist| checklist.requests.size > all }


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_user_is_authenticated, only: [:new,:create]

   def new
      @user = User.new
   end

   def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
         session_login(@user)
       else
          render 'new'
      end
   end

       #scope method
    def users_with_most_requests
      @users = User.users_with_most_requests
    end

    def show
      @user = User.find_by_id(params[:id])
      @untaken_user_requests = UsersRequest.untaken_by_user(@user)
    end

    def edit
      @user = User.find_by_id(params[:id])
    end

    def update
      @user = User.find_by(id: params[:id])
      if @user.update(user_params)
        redirect_to user_path(@user)
      else
        render 'edit'
      end
    end


    private

    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation,
        request_ids: []
      )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-danger">
        <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>

  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/users/edit.html.erb
<h1>Update your Baby Party Guide</h1>

<%= render 'form' %>

app/views/users/finished_users_requests.erb
<h1>Finished Users Requests</h1>

<table class="table">


<% @users_requests.finished_users_requests.each do |users_request| %>
  <tr>
   <td><%= users_request.item %></td>
  </tr>

  <% end %>
</table>
 <p><%= link_to "Create a New Request Checklist", new_user_checklist_path(current_user) %></p>

<div>

app/views/users/new.html.erb
<h1>Create a New Baby Party Guide</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div>
    <div>
    <% if current_user == @user %>
        <% unless @untaken_user_requests.empty? %>
            <p class="text-warning"><b>This is a baby party help request, please accept:</b></p>
                <table class="table">
                <tbody>
                <tr>
                    <th>Requests &nbsp;</th>
                    <th>Accept &nbsp;</th>
                </tr>
                <% @untaken_user_requests.each do |user_request| %>
                    <tr>
                        <td><%= link_to user_request.request.item, user_request_path(user_request.user, user_request.request) %></td>
                        <td>
                        <%= form_for(user_request, url: users_request_path(user_request), method: :patch) do |f| %>
                        <%= f.hidden_field :taken, value: true %>
                       <%= f.submit "Accept Request" %>
                   <% end %>
                   </td>
               </tr>
           <% end %>
           </tbody>
           </table>
   <% end %>
  </div>
</div>
<div>
        <h1><%= @user.name %></h1>
        <p><%= link_to "Edit Info", edit_user_path(@user) %></p>
        <h2 class="text-secondary">Your Checklists:</h2>
    <% else %>
        <h1><%= @user.name %>'s Page</h1>
        <h2 class="text-secondary">Their Checklists:</h2>
    <% end %>
    <div>
        <table class="table">
            <tbody>
                <tr>
                  <th>Item &nbsp;</th>
                    <th>Finished/Unfinished &nbsp;</th>
                    <th>Open Checklist &nbsp;</th>
                </tr>
                <% @user.checklists.each do |checklist| %>
                    <tr>
                        <td><%= checklist.item %></td>
                    <% if checklist.checklist_finished? %>
                        <td class="text-success">Finished</td>
                    <% else %>
                        <td class="text-danger">Unfinished</td>
                    <% end %>
                    <td><%= link_to "Open", user_checklist_path(@user, checklist) %></td>
                <% end %>
                </tr>
            </tbody>
        </table
        <% if current_user == @user %>
           <p><%= link_to "New Checklist", new_user_checklist_path(@user) %></p>
       <% end %>
   </div>
   <div>
   <% if current_user == @user %>
       <h2 class="text-secondary">Your Requests:</h2>
       <% else %>
       <h2 class="text-secondary">Their Requests:</h2>
   <% end %>
       <table class="table">
       <table class="table">
       <tbody>
           <tr>
              <th>Item</th>
              <th>Finished/Unfinished</th>
              <th>Taken/Untaken</th>
             </tr>
             <% @user.requests.each do |request| %>
                 <tr>
                     <td><%= request.item %></td>
                     <% if request.finished %>
                     <td class="text-success"><%= request.status %></td>
                     <% else %>
                     <td class="text-danger"><%= request.status %></td>
                     <% end %>
                     <% if request.user_taken?(@user) %>
                     <td class="text-success">taken</td>
                     <% else %>
                     <td class="text-warning">untaken</td>
                     <% end %>
                     <td><%= link_to "See Request", user_request_path(@user, request) %></td>
             <% end %>
             </tr>
         </tbody>
         </table>
     </div>
 </div>

app/views/users/users_with_most_requests.erb
<h1>Users with Most Requests</h1>

<table class="table">


<% @users.each do |user| %>
  <tr>
   <td><%= user.name %></td>
  </tr>

  <% end %>
</table>
 <p><%= link_to "Create a New Request Checklist", new_user_checklist_path(current_user) %></p>