config/routes.rb
Rails.application.routes.draw do

    root "welcome#home"
    get '/signup' => 'users#new'
    get '/login' => 'session#new'
    post '/login' => 'session#create'
    get '/auth/facebook/callback' => 'session#create'
    get '/logout' => 'session#destroy'

    get '/users/users_with_most_requests' => 'users#users_with_most_requests'
    get '/requests/finished_requests' => 'requests#finished_requests'
    get 'requests/unfinished_requests' => 'requests#unfinished_requests'
  #  get '/requests/whatever' => 'checklists#something'




    resources :requests, only: [:create, :destroy, :edit, :update] do
      resources :users, only: [:show]
     end

     resources :checklists, only: [:index, :show, :create, :update, :destroy] do
       resources :requests, only: [:new, :show, :edit, :update, :destroy]
     end

     resources :users, only: [:create, :destroy, :edit, :update, :show] do
       resources :checklists, only: [:new, :edit, :show, :update, :destroy]
     end

     resources :users do
       resources :requests, only: [:show, :edit]
     end

     resources :users_requests, only: [:update]

     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :verify_user_is_authenticated, only: [:home]
  def home
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<div>
    <% if current_user %>
        <h1>Welcome <%= current_user.name %>!</h1>
        <h2>Click on checklists to see current requests or to create new ones.</h2>
    <div>
    <table class="table">
        <tbody>
            <tr>
                <th>Item &nbsp;</th>
                <th>Finshed/Unfinished &nbsp;</th>
                <th>Taken/Untaken &nbsp;</th>
                </tr>
                <% current_user.requests.each do |request| %>
                    <tr>
                        <td><%= request.item %></td>

                        <% if request.finished %>
                        <td class="text-success"><%= request.status %></td>
                      <% else %>
                        <td class="text-danger"><%= request.status %></td>
                        <% end %>

                        <% if request.user_taken?(current_user) %>
                        <td class="text-success">Taken</td>
                     <% else %>
                        <td class="text-warning">Untaken</td>
                        <% end %>

                        <td><%= link_to "See Request", user_request_path(current_user, request) %></td>
                <% end %>
              </tr>
         </tbody>
     </table>
     </div>

     <p><%= link_to "Log Out", logout_path %></p>

     <% else %>
        <div>
            <h1>Welcome to the Ultimate Baby Party Planning Guide!</h1>

            <p class="text-secondary">This is the perfect place to organize the best baby party with a little help from your friends.</p>

            <p class="text-secondary">Please Sign Up or Log In.</p>
          </div>
              <p><%= link_to "Sign Up", signup_path %></p>
              <p><%= link_to "Log In", login_path %></p>
              <p><%= link_to('Log in with Facebook', '/auth/facebook') %></p>
      <% end %>
  </div>