config/routes.rb
Rails.application.routes.draw do

    root "welcome#home"
    get '/signup' => 'users#new'
    get '/login' => 'session#new'
    post '/login' => 'session#create'
    get '/auth/facebook/callback' => 'session#create'
    get '/logout' => 'session#destroy'

    get '/users/users_with_most_requests' => 'users#users_with_most_requests'
    get '/requests/finished_requests' => 'requests#finished_requests'
    get 'requests/unfinished_requests' => 'requests#unfinished_requests'
  #  get '/requests/whatever' => 'checklists#something'




    resources :requests, only: [:create, :destroy, :edit, :update] do
      resources :users, only: [:show]
     end

     resources :checklists, only: [:index, :show, :create, :update, :destroy] do
       resources :requests, only: [:new, :show, :edit, :update, :destroy]
     end

     resources :users, only: [:create, :destroy, :edit, :update, :show] do
       resources :checklists, only: [:new, :edit, :show, :update, :destroy]
     end

     resources :users do
       resources :requests, only: [:show, :edit]
     end

     resources :users_requests, only: [:update]

     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   end

app/models/request.rb
class Request < ApplicationRecord
  validates :item, presence: true

  has_many :users_request
  has_many :users, through: :users_request
  belongs_to :checklist

  def status
    finished ? 'Finished' : 'Unfinished'
  end

  def user_taken?(user)
    users_request.find {|user_request|user_request.user_id == user.id}.taken
  end

  def untaken_users
    users.select do |user|
      user_taken?(user) == false
    end
  end

  def finished_label
    finished ? 'Finished' : 'Update Status'
  end

  def finished_klass
    finished ? 'Text-success' : 'Text-danger'
  end


  #Client.where.not(locked: true)

  #Request.where.not(finished: true)
  scope :finished_requests, -> { where('finished')}
  #scope :requests_with_kids_in_note, -> { select('note').where(:kids)}
  scope :unfinished_requests, -> { where.not('finished')}
#{ where(:note_kids)}
# {where(note_contains_kids :true)}
#scope :requests_with_kids_in_note, -> { where('note').includes(content: "kids")}
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  #scope method
  def finished_requests
    @requests = current_user.requests.finished_requests
  end

  def unfinished_requests
    @requests = current_user.requests.unfinished_requests
  end

  def new
    @request = Request.new(checklist_id: params[:checklist_id])
  end

  def create
    @request = Request.new(request_params)
      if @request.save
        redirect_to checklist_request_path(@request.checklist, @request)
      else
        render 'new'
      end
  end

  def show
    @request = Request.find_by(id: params[:id])
    @user_request = @request.users_request.find{|user_request|user_request.user_id == current_user.id}
  end

  def edit
    @request = Request.find_by(id: params[:id])
  end

  def update
    @request = Request.find_by(id: params[:id])
      if @request.update(request_params)
         redirect_to checklist_request_path(@request.checklist, @request)
      else
         render 'edit'
      end
  end

  def destroy
    request = Request.find_by(id: params[:id])
    @checklist = request.checklist
    request.destroy
    redirect_to checklist_path(@checklist)
  end

   private

  def request_params
    params.require(:request).permit(
      :item,
      :note,
      :checklist_id,
      :finished,
      user_ids: []
      )
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>

   <% if @request.errors.any? %>
   <div id="error_explanation">
    <h2 class="text-danger">
      <%= pluralize(@request.errors.count, "error") %> prohibited this list from being saved:
    </h2>

    <ul>
        <% @request.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :item %>
  <%= f.text_field :item %>

  <%= f.label :note %>
  <%= f.text_field :note %>

  <%= f.hidden_field :checklist_id %>

  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/requests/edit.html.erb
<h2>Edit Your Request</h2>

<%= render 'form' %>

app/views/requests/finished_requests.erb
<h1>Your Finished Requests</h1>

<table class="table">

<% @requests.each do |request| %>
  <tr>
   <td><%= request.item %></td>
  </tr>

  <% end %>
</table>



 <p><%= link_to "Create a New Request Checklist", new_user_checklist_path(current_user) %></p>

app/views/requests/new.html.erb
<h2>Create a Request for your Checklist</h2>

<%= render 'form' %>

app/views/requests/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm">
          <h2><%= @request.item %></h2>
          <% if @request.finished %>
              <p class="text-info"><span class="border border-success">Note: <%= @request.note %></span></p>
        <% else %>
              <p class="text-info"><span class="border border-danger">Note: <%= @request.note %></span></p>
            <% end %>
            <p class="text-secondary">Return to Checklist: <%= link_to @request.checklist.item, checklist_path(@request.checklist) %></p>
            <% if !@request.finished %>
                <p class="text-info"><span class="text-danger">Status: <%= @request.status %></span></p>
            <% end %>
             <%= form_for(@request, url: {controller: 'requests', action: 'update'}) do |f| %>
                <% if @request.finished %>
                <%= f.hidden_field :finished, value: false  %>
                <% else %>
                <%= f.hidden_field :finished, value: true %>
                <% end %>
                <%= f.submit @request.finished_label, class: @request.finished_klass %>
            <% end %>
          </div>
         <div class="col-sm">
             <% if current_user.checklist_requests(@request.checklist).include?(@request) %>
                 <p><%= link_to "Edit Request", edit_user_request_path(@request) %></p>
                 <p><b>Give this request to a User:</b></p>
                 <%= form_for @request, url: {controller: 'requests', action: 'update'} do |f|%>
                     <%= collection_check_boxes(:request, :user_ids, User.all, :id, :name) %>
                     <br>
                     <%= f.submit "Update Requests" %>
                 <% end %>
             <% end %>
         <div class="p-3">
             <p><b>Users Given Request:</b></p>
             <% if @request.users %>
                <ul>
                <% @request.users.each do |user| %>
                    <li>
                        <p><%= link_to user.name, user_path(user) %></p>
                        <br>
                        <% if user == current_user && !@user_request.taken %>
                        <%= form_for(@user_request, url: users_request_path(@user_request), method: :patch) do |f| %>
                            <%= f.hidden_field :taken, value: true %>
                            <%= f.submit "Accept Request", class: 'text-warning' %>
                        <% end %>
                      <% elsif @request.untaken_users.include?(user) %>
                          <span class="text-warning">Untaken</span>
                        <% end %>
                    </li>
                <% end %>
                </ul>
            <% end %>
        </div>
        </div>
    </div>
        <% if @request.checklist.user == current_user %>
            <p>
                <%= form_for @request, method: :delete do |f|%>
                    <%= f.submit "Delete Request", class: "text-danger" %>
                <% end %>
            </p>
        <% end %>
</div>

app/views/requests/unfinished_requests.erb
<h1>Requests that are Unfinished</h1>

<table class="table">

<% @requests.each do |request| %>
  <tr>
   <td><%= request.item %></td>
  </tr>

  <% end %>
</table>



 <p><%= link_to "Create a New Request Checklist", new_user_checklist_path(current_user) %></p>