config/routes.rb
Rails.application.routes.draw do

    root "welcome#home"
    get '/signup' => 'users#new'
    get '/login' => 'session#new'
    post '/login' => 'session#create'
    get '/auth/facebook/callback' => 'session#create'
    get '/logout' => 'session#destroy'

    get '/users/users_with_most_requests' => 'users#users_with_most_requests'
    get '/requests/finished_requests' => 'requests#finished_requests'
    get 'requests/unfinished_requests' => 'requests#unfinished_requests'
  #  get '/requests/whatever' => 'checklists#something'




    resources :requests, only: [:create, :destroy, :edit, :update] do
      resources :users, only: [:show]
     end

     resources :checklists, only: [:index, :show, :create, :update, :destroy] do
       resources :requests, only: [:new, :show, :edit, :update, :destroy]
     end

     resources :users, only: [:create, :destroy, :edit, :update, :show] do
       resources :checklists, only: [:new, :edit, :show, :update, :destroy]
     end

     resources :users do
       resources :requests, only: [:show, :edit]
     end

     resources :users_requests, only: [:update]

     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   end

app/models/checklist.rb
class Checklist < ApplicationRecord
    validates :item, presence: true

    has_many :requests
    belongs_to :user

    def checklist_finished?
        !requests.any?{|request| request.status == "Unfinished"}
    end

    accepts_nested_attributes_for :requests

    def self.search(search)
      if search
          where('item LIKE ?', "%#{search}%")
        else
         Checklist.all
      end
    end

end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController

  def index
   #@checklists = Checklist.all
   @checklists = Checklist.search(params[:search])
  end

  def new
    @checklist = Checklist.new(user_id: current_user.id)
  end

  def create
    @checklist = Checklist.new(checklist_params)
      if @checklist.save
         redirect_to user_checklist_path(current_user, @checklist)
    else
        flash[:notice] = "Your checklist creation was unsuccessful"
        render 'new'
      end
  end

 def show
    @checklist = Checklist.find_by(id: params[:id])
 end

 def edit
   @checklist = Checklist.find_by(id: params[:id])
 end

 def update
   @checklist = Checklist.find_by(id: params[:id])
    if @checklist.update(checklist_params)
      redirect_to checklist_path(@checklist)
   else
       flash[:notice] = "Something went wrong, please try again"
       render 'edit'
    end
 end

  def destroy
    checklist = Checklist.find_by(id: params[:id])
    checklist.destroy
    redirect_to user_path(current_user)
  end

    private

 def checklist_params
    params.require(:checklist).permit(
      :item,
      :user_id
    #  :search
    )
 end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/_form.html.erb
<%= form_for @checklist do |f| %>

   <% if @checklist.errors.any? %>
   <div id="error_explanation">
      <h2 class="text-danger">
        <%= pluralize(@checklist.errors.count, "error") %> prohibited this list from being saved:
      </h2>

      <ul>
      <% @checklist.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

  <%= f.label :item %>
  <%= f.text_field :item %>
  <br>
  <%= f.hidden_field :user_id %>

  <%= f.submit class: "btn-primary" %>
<% end %>

app/views/checklists/edit.html.erb
<h1>Edit Your Checklist Items</h1>

<%= render 'form' %>

app/views/checklists/index.html.erb
<div>
    <table class="table">
    <tbody>
        <tr>
            <th>Checklists &nbsp;</th>
            <th>Finished/Unfinished &nbsp;</th>
            <th>See Requests &nbsp;</th>
        </tr>
        <% @checklists.each do |checklist| %>
        <tr>
            <td><%= checklist.item %></td>
            <% if checklist.checklist_finished? %>
                <td class="text-success">Finished</td>
            <% else %>
                <td class="text-danger">Unfinished</td>
            <% end %>
            <td><%= link_to "Open", checklist_path(checklist) %></td>
        <% end %>
        </tr>
        </tbody>
    </table>
    <br><br>

    <h4>Search the Checklists</h4>
     <%= form_tag(checklists_path, method: "get") do %>
      <%= text_field_tag(:search)%>
      <%= submit_tag("Search") %>
     <% end %>
    <br><br>
    <div>
      <%= link_to "Show the Users with Most Requests", users_users_with_most_requests_path(@user)%><br><br>
    </div>

    <div>
      <%= link_to "Finished Users Requests", requests_finished_requests_path(@request)%><br><br>
    </div>

    <div>
      <%= link_to "Unfinished Requests", requests_unfinished_requests_path(@request)%><br><br>
    </div>



    <p><%= link_to "Create a New Request Checklist", new_user_checklist_path(current_user) %></p>

</div>

app/views/checklists/new.html.erb
<h1>Create a New Checklist</h1>

<%= render 'form' %>

app/views/checklists/show.html.erb
<h1><%= @checklist.item %></h1>

<h3 class="text-secondary">Created by: <%= link_to @checklist.user.name, user_path(@checklist.user) %> </h3>

<% if current_user.checklists.include?(@checklist) %>
    <p><%= link_to "Change Item", edit_user_checklist_path(@checklist) %></p>

    <p><%= link_to "Add a Request", new_checklist_request_path(@checklist) %></p>

<% end %>

<div>

    <table class="table">
      <tbody>
      <tr>
          <th>Request &nbsp;</th>
          <th>Finished/Unfinished &nbsp;</th>
      </tr>

      <% @checklist.requests.each do |request| %>
          <tr>
              <td><%= request.item %></td>
              <% if request.finished %>
              <td class="text-success"><%= request.status %></td>
              <% else %>
              <td class="text-danger"><%= request.status %></td>
              <% end %>
              <td><%= link_to "See Request", checklist_request_path(@checklist, request) %></td>

          <% end %>
          </tr>

      </tbody>
      </table>

         <% if current_user.checklists.include?(@checklist) %>
         <p>
           <%= form_for @checklist, method: :delete do |f| %>
               <%= f.submit "Delete Checklist", class: "text-danger" %>
           <% end %>
       </p>

<% end %>

</div>

app/views/checklists/users_with_most_requests.erb
<h1>Users with Most Requests</h1>

<table class="table">


<% Checklist.users_with_most_requests.each do |t| %>
  <tr>
   <td><%= t.user.name %></td>
  </tr>

  <% end %>
</table>
 <p><%= link_to "Create a New Request Checklist", new_user_checklist_path(current_user) %></p>

<div>